from enum import StrEnum


class Role(StrEnum):
    EMPLOYEE = "EMPLOYEE"
    MANAGER = "MANAGER"
    TEAM_LEAD = "TEAM_LEAD"
    DEPARTMENT_HEAD = "DEPARTMENT_HEAD"
    EXECUTIVE = "EXECUTIVE"
    SALES_DIRECTOR = "SALES_DIRECTOR"
    SALES_MANAGER = "SALES_MANAGER"
    ACCOUNT_MANAGER = "ACCOUNT_MANAGER"
    SALES_OPERATIONS = "SALES_OPERATIONS"
    PROJECT_LEAD = "PROJECT_LEAD"
    PROJECT_MEMBER = "PROJECT_MEMBER"
    HR_ADMIN = "HR_ADMIN"
    FINANCE_ADMIN = "FINANCE_ADMIN"
    LEGAL_ADMIN = "LEGAL_ADMIN"
    IT_ADMIN = "IT_ADMIN"
